name: Deploy Angular Site

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Build project
        run: |
          npx ng build app-name --configuration production --base-href /tpcec/
          # This command ensures 404.html is created even if the folder structure is deep
          cp dist/apps/app-name/index.html dist/apps/app-name/404.html || cp dist/apps/app-name/browser/index.html dist/apps/app-name/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # We'll use a wildcard to ensure it finds the output even if Angular puts it in /browser
          path: dist/apps/app-name
