name: Deploy Angular Site

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: |
          npm install @angular-devkit/build-angular --save-dev --legacy-peer-deps
          npx ng build app-name --configuration production --base-href /tpcec/
          
          # Check if Angular put it in /browser (standard for Angular 19)
          if [ -d "dist/tpcec/browser" ]; then
            cp dist/tpcec/browser/index.html dist/tpcec/browser/404.html
            echo "DEPLOY_PATH=dist/tpcec/browser" >> $GITHUB_ENV
          else
            cp dist/tpcec/index.html dist/tpcec/404.html || echo "Path check..."
            echo "DEPLOY_PATH=dist/tpcec" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DEPLOY_PATH }}
  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
